server:
   port: 8090
spring:
   cloud:
      config:
         server:
           git:
            default-label: main
            uri: https://github.com/hectorhuamanflores/project-one-config-server
   application:
      name: config-server